### ISSUE TITLE
Emails to you are bouncing

### ISSUE THREAD

**Issue by nbolton** [flaviusbohaciuc/my-resume#1]
Hey, I tried to email you about the job you applied to, but it bounced: https://mail.mixmax.com/m/NpkCm4BCMZWq3xyWI

**Comment by thatflav** [comment]
Hey, I've just seen that is a typo. <gmaill.com> the L is doubled.

This is my email:  flaviusbohaciuc@gmail.com

**Comment by nbolton** [comment]
Yep! Spotted that. Sent you a new email 👍
